spring.docker.compose.enabled=false
server.port=9001

logging.level.com.aadhar.vault=DEBUG
   

ac=A100078
sa=A100078
lk=47fa9a35-afdf-439a-aa88-eb9585b7dab9
#vaulturl=https://sp.epramaan.in:8038/securevault/
vaulturl=https://advpreprod.epramaan.in/securevault/
# https://sp.epramaan.in:8038/vault/
#http://14.139.127.135:8038/vault/
configpara=true
debug=false