#certpath=D:\\New Ekisan\\ekisan_aadhar_vault\\securevault\\RSA_TEST_KEYS.cer
#certpath=/home/ubuntu/aadharVault/vault/securevault/RSA_TEST_KEYS.cer
certpath=/app/RSA_TEST_KEYS.cer
configpara=true
ac=A100078
sa=A100078
lk=47fa9a35-afdf-439a-aa88-eb9585b7dab9
#vaulturl=https://sp.epramaan.in:8038/securevault/
vaulturl=https://advpreprod.epramaan.in/securevault/
debug=false