#certpath:securevault/RSA_TEST_KEYS 1.cer
certpath:/home/ubuntu/aadharVault/vault/securevault/RSA_TEST_KEYS 1.cer
configpara=true
ac=A100078
sa=A100078
lk=47fa9a35-afdf-439a-aa88-eb9585b7dab9
vaulturl=https://sp.epramaan.in:8038/securevault/